; Script generated by Inno Setup Script Wizard
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ТВ-телеметрия Квадросима"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Quadrosim Team"
#define MyAppExeName "QuadrosimTelemetry.exe"
#define MyAppURL "https://github.com/quadrosim/telemetry"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
AppId={{A3B8F7C2-1D4E-4A9B-8C7D-6E5F4A3B2C1D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=
OutputDir=installer_output
OutputBaseFilename=QuadrosimTelemetry_Setup_{#MyAppVersion}
SetupIconFile=compiler:BlueModern.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "english"; MessagesFile: "compiler:Languages\English.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 6.1; Check: not IsAdminInstallMode

[Files]
Source: "dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
Filename: "{app}\python.exe"; Parameters: "-m ensurepip --upgrade"; Flags: runhidden
Filename: "{app}\python.exe"; Parameters: "-m pip install -r requirements.txt --quiet"; WorkingDir: "{app}"; Flags: runhidden
Filename: "{cmd}"; Parameters: "/c tesseract --version >nul 2>&1 || echo Tesseract not found"; Flags: runhidden

[Code]
var
  TesseractPathPage: TInputDirWizardPage;
  PythonInstalled: Boolean;
  TesseractInstalled: Boolean;

function InitializeSetup(): Boolean;
var
  ResultCode: Integer;
begin
  Result := True;
  
  // Проверка Python
  PythonInstalled := Exec('python', '--version', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  if not PythonInstalled then
    PythonInstalled := Exec('python3', '--version', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  
  if not PythonIncluded then
  begin
    if MsgPrompt('Python не найден в системе. Продолжить установку (включает встроенный Python)?', 'Предупреждение', MB_YESNO) = ID_NO then
      Result := False;
  end;
  
  // Проверка Tesseract
  TesseractInstalled := Exec('tesseract', '--version', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  
  if not TesseractInstalled then
  begin
    TesseractPathPage := CreateInputDirPage(wpSelectDir,
      'Установка Tesseract OCR', 'Tesseract OCR не найден в системе.',
      'Выберите папку с установленным Tesseract OCR или нажмите Отмена для пропуска.',
      False, '');
    TesseractPathPage.Add('Путь к Tesseract OCR');
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  TesseractPath: String;
begin
  if CurStep = ssPostInstall then
  begin
    // Добавляем Tesseract в PATH если указан
    if Assigned(TesseractPathPage) then
    begin
      TesseractPath := TesseractPathPage.Values[0];
      if DirExists(TesseractPath) then
      begin
        RegWriteStringValue(HKEY_LOCAL_MACHINE,
          'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
          'Path', '%PATH%;' + TesseractPath);
        MsgBox('Tesseract OCR добавлен в системный PATH. Может потребоваться перезагрузка.', mbInformation, MB_OK);
      end;
    end;
  end;
end;

[InstallDelete]
Type: filesandordirs; Name: "{app}\__pycache__"
Type: filesandordirs; Name: "{app}\*.pyc"

[UninstallDelete]
Type: filesandordirs; Name: "{app}\logs"
Type: filesandordirs; Name: "{app}\reports"
Type: filesandordirs; Name: "{app}\__pycache__"
